services:
  - type: web
    name: svc-mcp-datadog
    runtime: python
    buildCommand: pip install uv && uv sync
    startCommand: uv run python -m src.server
    autoDeploy: true
    region: oregon
